[2025-01-16 19:52:28,141] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-09T00:00:00+00:00 [queued]>
[2025-01-16 19:52:28,156] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-09T00:00:00+00:00 [queued]>
[2025-01-16 19:52:28,156] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2025-01-16 19:52:28,158] {taskinstance.py:1096} INFO - Starting attempt 3 of 4
[2025-01-16 19:52:28,158] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2025-01-16 19:52:28,174] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2016-12-09T00:00:00+00:00
[2025-01-16 19:52:28,176] {standard_task_runner.py:52} INFO - Started process 326756 to run task
[2025-01-16 19:52:28,190] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', '2016-12-09T00:00:00+00:00', '--job-id', '30', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmptw0opdki', '--error-file', '/tmp/tmp0azq0qp7']
[2025-01-16 19:52:28,191] {standard_task_runner.py:77} INFO - Job 30: Subtask pyspark_train_classifier_model
[2025-01-16 19:52:28,245] {logging_mixin.py:109} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-09T00:00:00+00:00 [running]> on host ibdn-VirtualBox
[2025-01-16 19:52:28,296] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2016-12-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2016-12-09T00:00:00+00:00
[2025-01-16 19:52:28,297] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2025-01-16 19:52:28,297] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nspark-submit --master local[8]   /home/ibdn/BDFI/practica_creativa//resources/train_spark_mllib_model.py   /home/ibdn/BDFI/practica_creativa/']
[2025-01-16 19:52:28,304] {subprocess.py:74} INFO - Output:
[2025-01-16 19:52:30,519] {subprocess.py:78} INFO - 25/01/16 19:52:30 WARN Utils: Your hostname, ibdn-VirtualBox resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
[2025-01-16 19:52:30,519] {subprocess.py:78} INFO - 25/01/16 19:52:30 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-01-16 19:52:31,260] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO SparkContext: Running Spark version 3.3.0
[2025-01-16 19:52:31,339] {subprocess.py:78} INFO - 25/01/16 19:52:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-16 19:52:31,443] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO ResourceUtils: ==============================================================
[2025-01-16 19:52:31,451] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-01-16 19:52:31,451] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO ResourceUtils: ==============================================================
[2025-01-16 19:52:31,451] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO SparkContext: Submitted application: train_spark_mllib_model.py
[2025-01-16 19:52:31,467] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-01-16 19:52:31,496] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO ResourceProfile: Limiting resource is cpu
[2025-01-16 19:52:31,509] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-01-16 19:52:31,549] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO SecurityManager: Changing view acls to: ibdn
[2025-01-16 19:52:31,550] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO SecurityManager: Changing modify acls to: ibdn
[2025-01-16 19:52:31,550] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO SecurityManager: Changing view acls groups to:
[2025-01-16 19:52:31,550] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO SecurityManager: Changing modify acls groups to:
[2025-01-16 19:52:31,550] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ibdn); groups with view permissions: Set(); users  with modify permissions: Set(ibdn); groups with modify permissions: Set()
[2025-01-16 19:52:31,896] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO Utils: Successfully started service 'sparkDriver' on port 33969.
[2025-01-16 19:52:31,940] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO SparkEnv: Registering MapOutputTracker
[2025-01-16 19:52:31,979] {subprocess.py:78} INFO - 25/01/16 19:52:31 INFO SparkEnv: Registering BlockManagerMaster
[2025-01-16 19:52:32,018] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-01-16 19:52:32,019] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-01-16 19:52:32,028] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-01-16 19:52:32,051] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-245e9f1a-de3f-4098-9c39-54d623a44390
[2025-01-16 19:52:32,080] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-01-16 19:52:32,117] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-01-16 19:52:32,344] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-01-16 19:52:32,460] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO Executor: Starting executor ID driver on host 10.0.2.15
[2025-01-16 19:52:32,467] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-01-16 19:52:32,493] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36113.
[2025-01-16 19:52:32,493] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO NettyBlockTransferService: Server created on 10.0.2.15:36113
[2025-01-16 19:52:32,493] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-01-16 19:52:32,494] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.0.2.15, 36113, None)
[2025-01-16 19:52:32,497] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO BlockManagerMasterEndpoint: Registering block manager 10.0.2.15:36113 with 434.4 MiB RAM, BlockManagerId(driver, 10.0.2.15, 36113, None)
[2025-01-16 19:52:32,508] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.0.2.15, 36113, None)
[2025-01-16 19:52:32,510] {subprocess.py:78} INFO - 25/01/16 19:52:32 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.0.2.15, 36113, None)
[2025-01-16 19:52:33,103] {subprocess.py:78} INFO - 25/01/16 19:52:33 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-01-16 19:52:33,114] {subprocess.py:78} INFO - 25/01/16 19:52:33 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmp5glopniy/spark-warehouse'.
[2025-01-16 19:52:33,223] {local_task_job.py:209} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2025-01-16 19:52:33,243] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 326756
[2025-01-16 19:52:33,244] {taskinstance.py:1236} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-16 19:52:33,244] {subprocess.py:88} INFO - Sending SIGTERM signal to process group
[2025-01-16 19:52:33,248] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 171, in execute
    output_encoding=self.output_encoding,
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 76, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1238, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-01-16 19:52:33,252] {taskinstance.py:1513} INFO - Marking task as FAILED. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20161209T000000, start_date=20250116T185228, end_date=20250116T185233
[2025-01-16 19:52:33,621] {process_utils.py:66} INFO - Process psutil.Process(pid=326880, status='terminated', started='19:52:30') (326880) terminated with exit code None
[2025-01-16 19:52:33,621] {process_utils.py:66} INFO - Process psutil.Process(pid=326756, status='terminated', exitcode=1, started='19:52:27') (326756) terminated with exit code 1
[2025-01-16 19:52:34,100] {process_utils.py:66} INFO - Process psutil.Process(pid=326758, status='terminated', started='19:52:28') (326758) terminated with exit code None
