[2025-01-17 00:53:03,958] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-20T00:00:00+00:00 [queued]>
[2025-01-17 00:53:03,963] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-20T00:00:00+00:00 [queued]>
[2025-01-17 00:53:03,963] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2025-01-17 00:53:03,963] {taskinstance.py:1096} INFO - Starting attempt 3 of 4
[2025-01-17 00:53:03,963] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2025-01-17 00:53:03,989] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2016-12-20T00:00:00+00:00
[2025-01-17 00:53:03,995] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', '2016-12-20T00:00:00+00:00', '--job-id', '62', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpfno7rfkg', '--error-file', '/tmp/tmpmn4c13xk']
[2025-01-17 00:53:03,998] {standard_task_runner.py:52} INFO - Started process 346011 to run task
[2025-01-17 00:53:04,001] {standard_task_runner.py:77} INFO - Job 62: Subtask pyspark_train_classifier_model
[2025-01-17 00:53:04,081] {logging_mixin.py:109} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2016-12-20T00:00:00+00:00 [running]> on host ibdn-VirtualBox
[2025-01-17 00:53:04,107] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2016-12-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2016-12-20T00:00:00+00:00
[2025-01-17 00:53:04,108] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2025-01-17 00:53:04,108] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nspark-submit --master local[8]   /home/ibdn/BDFI/practica_creativa//resources/train_spark_mllib_model.py   /home/ibdn/BDFI/practica_creativa/']
[2025-01-17 00:53:04,113] {subprocess.py:74} INFO - Output:
[2025-01-17 00:53:05,880] {subprocess.py:78} INFO - 25/01/17 00:53:05 WARN Utils: Your hostname, ibdn-VirtualBox resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
[2025-01-17 00:53:05,884] {subprocess.py:78} INFO - 25/01/17 00:53:05 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-01-17 00:53:07,293] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO SparkContext: Running Spark version 3.3.0
[2025-01-17 00:53:07,374] {subprocess.py:78} INFO - 25/01/17 00:53:07 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-17 00:53:07,532] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO ResourceUtils: ==============================================================
[2025-01-17 00:53:07,532] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-01-17 00:53:07,533] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO ResourceUtils: ==============================================================
[2025-01-17 00:53:07,533] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO SparkContext: Submitted application: train_spark_mllib_model.py
[2025-01-17 00:53:07,548] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-01-17 00:53:07,558] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO ResourceProfile: Limiting resource is cpu
[2025-01-17 00:53:07,560] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-01-17 00:53:07,606] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO SecurityManager: Changing view acls to: ibdn
[2025-01-17 00:53:07,607] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO SecurityManager: Changing modify acls to: ibdn
[2025-01-17 00:53:07,607] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO SecurityManager: Changing view acls groups to:
[2025-01-17 00:53:07,608] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO SecurityManager: Changing modify acls groups to:
[2025-01-17 00:53:07,608] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(ibdn); groups with view permissions: Set(); users  with modify permissions: Set(ibdn); groups with modify permissions: Set()
[2025-01-17 00:53:07,846] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO Utils: Successfully started service 'sparkDriver' on port 37911.
[2025-01-17 00:53:07,888] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO SparkEnv: Registering MapOutputTracker
[2025-01-17 00:53:07,941] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO SparkEnv: Registering BlockManagerMaster
[2025-01-17 00:53:07,963] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-01-17 00:53:07,963] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-01-17 00:53:07,963] {subprocess.py:78} INFO - 25/01/17 00:53:07 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-01-17 00:53:08,013] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-8aa4a29a-35e7-4989-8114-9f0354349ece
[2025-01-17 00:53:08,025] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-01-17 00:53:08,045] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-01-17 00:53:08,453] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-01-17 00:53:08,626] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO Executor: Starting executor ID driver on host 10.0.2.15
[2025-01-17 00:53:08,633] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-01-17 00:53:08,654] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37157.
[2025-01-17 00:53:08,654] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO NettyBlockTransferService: Server created on 10.0.2.15:37157
[2025-01-17 00:53:08,656] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-01-17 00:53:08,674] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.0.2.15, 37157, None)
[2025-01-17 00:53:08,674] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO BlockManagerMasterEndpoint: Registering block manager 10.0.2.15:37157 with 434.4 MiB RAM, BlockManagerId(driver, 10.0.2.15, 37157, None)
[2025-01-17 00:53:08,686] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.0.2.15, 37157, None)
[2025-01-17 00:53:08,689] {subprocess.py:78} INFO - 25/01/17 00:53:08 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.0.2.15, 37157, None)
[2025-01-17 00:53:09,026] {local_task_job.py:209} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2025-01-17 00:53:09,054] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 346011
[2025-01-17 00:53:09,055] {taskinstance.py:1236} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-17 00:53:09,055] {subprocess.py:88} INFO - Sending SIGTERM signal to process group
[2025-01-17 00:53:09,061] {process_utils.py:66} INFO - Process psutil.Process(pid=346139, status='terminated', started='00:53:06') (346139) terminated with exit code None
[2025-01-17 00:53:09,065] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 171, in execute
    output_encoding=self.output_encoding,
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 76, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/ibdn/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1238, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-01-17 00:53:09,071] {taskinstance.py:1513} INFO - Marking task as FAILED. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20161220T000000, start_date=20250116T235303, end_date=20250116T235309
[2025-01-17 00:53:09,129] {process_utils.py:66} INFO - Process psutil.Process(pid=346011, status='terminated', exitcode=1, started='00:53:03') (346011) terminated with exit code 1
[2025-01-17 00:53:09,326] {process_utils.py:66} INFO - Process psutil.Process(pid=346012, status='terminated', started='00:53:03') (346012) terminated with exit code None
[2025-01-17 00:53:09,326] {process_utils.py:66} INFO - Process psutil.Process(pid=346013, status='terminated', started='00:53:03') (346013) terminated with exit code None
